---
abstract: 'a high-level interface to cddb protocol servers (freedb and CDDB)'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires:
  Scalar::Util: 1.29
  Test::More: 0.98
  perl: 5.004
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CDDB
requires:
  Carp: 1.26
  Encode: 2.51
  HTTP::Request: 6.00
  IO::Socket: 1.31
  LWP: 6.05
  MIME::QuotedPrint: 3.13
  Mail::Header: 2.04
  Mail::Internet: 2.04
  Sys::Hostname: 1.11
  perl: 5.001
  strict: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CDDB
  homepage: http://search.cpan.org/dist/CDDB/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rcaputo/cddb-perl.git
version: 1.222
