---
abstract: 'a high-level interface to cddb protocol servers (freedb and CDDB)'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CDDB
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CDDB
  homepage: http://search.cpan.org/dist/CDDB
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rcaputo/cddb-perl.git
version: 1.221
